 name: Pre-release

 on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

 jobs:
   build:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2

     - name: Set up Go
       uses: actions/setup-go@v2
       with:
         go-version: 1.16

     - name: Go build
       run: go build .

     - name: Create Alfredworkflow package
       run: zip -j linguee-de-workflow.alfredworkflow linguee info.plist icons/*

     - name: Deploy pre-release
       uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: true
         title: "Development Build"
         files: |
           *.alfredworkflow
